### ISSUE TITLE
bash: path: No such file or directory

### ISSUE THREAD

**Issue by furycurry** [CN-TU/ids-backdoor#2]
whenever I am trying to run 
`$ ./learn.py --dataroot CAIA_backdoor_15.csv --method=rf --net <path to you random forest> --function prune_backdoor --backdoor --reduceValidationSet <fraction from 0 to 1 that indicates the fraction of the validation dataset that is going to be used> --nSteps 49 --pruneOnlyHarmless --depth` 
in the 
_~/Desktop/Research_papers/ids-backdoor-master_ directory, I am facing this error.

![image](https://user-images.githubusercontent.com/58500422/155450287-8fd46e6e-e4b6-405e-893a-3955f359de57.png)

**Comment by alexhartl** [comment]
You forgot to replace `--net <path to you random forest>` and `--reduceValidationSet <fraction from 0 to 1 that indicates the fraction of the validation dataset that is going to be used>` with your true values.

**Comment by furycurry** [comment]
> You forgot to replace `--net <path to you random forest>` and `--reduceValidationSet <fraction from 0 to 1 that indicates the fraction of the validation dataset that is going to be used>` with your true values.

Thanks
